### ISSUE TITLE
访问速度有点慢？顺便建议内容可以丰富一些

### ISSUE THREAD

**Issue by LadderOperator** [idealclover/Life-in-NJU#6]
👍

如果作为主页的话，加载速度太慢其实也是硬伤吧……我现在挂了梯子才进了去的

另外，个人感觉可以参照另一个个人项目[南大生活指南·语雀](https://www.yuque.com/gerongcun/njugeo/njuguidebook)，一起合作丰富下网页内容（当然因为每年不一样有些东西会改变，但是发布的学校单位基本是一致的），比如：
+ 入学专题：医保之类的常规通知，在哪个网站可以看通知这种，只需要网站主页即可
+ 生活专题：这类链接基本稳定不变，可具体到页面这样

**Comment by idealclover** [comment]
加载慢是因为 github page 在国内不稳，刚刚自己用国内服务器搭了个备用网站

https://nju.idealclover.cn/

OK 这就把这个项目和里面的一些链接搬过来w 感谢感谢！！
